apiVersion: v1
kind: Service
metadata:
  labels:
    service: company-api
  name: company-api
spec:
    type: LoadBalancer
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: company-api
