apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: company-api
  name: company-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: company-api
  template:
    metadata:
      labels:
        service: company-api
    spec:
      containers:
      - image: lienas/company-api
        name: company-api
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        env:
        - name: MYSQL_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: prepo-env-config
              key: MYSQL_DB_NAME
        - name: MYSQL_URL
          valueFrom:
            configMapKeyRef:
              name: prepo-env-config
              key: MYSQL_URL
        - name: MYSQL_PWD
          valueFrom:
            secretKeyRef:
              name: prepo-env-secret
              key: MYSQL_PWD
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: prepo-env-secret
              key: MYSQL_USER
      restartPolicy: Always
